xcopy /Y .\11-MasterDetailThreeLevels\src\wpf\MasterDetailThreeLevel\AssemblyInfo.cs .\13-TemplatingItems\src\wpf\TemplatingItems
xcopy /Y .\11-MasterDetailThreeLevels\src\wpf\MasterDetailThreeLevel\AssemblyInfo.cs .\14-SortingGroups\src\wpf\SortingGroups
xcopy /Y .\11-MasterDetailThreeLevels\src\wpf\MasterDetailThreeLevel\AssemblyInfo.cs .\15-GroupingTreeView\src\wpf\GroupingTreeView
xcopy /Y .\11-MasterDetailThreeLevels\src\wpf\MasterDetailThreeLevel\AssemblyInfo.cs .\16-GroupByType\src\wpf\GroupByType
xcopy /Y .\11-MasterDetailThreeLevels\src\wpf\MasterDetailThreeLevel\AssemblyInfo.cs .\17-BoundListView\src\wpf\BoundListView
xcopy /Y .\11-MasterDetailThreeLevels\src\wpf\MasterDetailThreeLevel\AssemblyInfo.cs .\18-ThreeLevelMasterDetailADO\src\wpf\ThreeLevelMasterDetailADO
xcopy /Y .\11-MasterDetailThreeLevels\src\wpf\MasterDetailThreeLevel\AssemblyInfo.cs .\19-ObjectDataProviderSample\src\wpf\ObjectDataProviderSample
xcopy /Y .\11-MasterDetailThreeLevels\src\wpf\MasterDetailThreeLevel\AssemblyInfo.cs .\20-InsertingSeparators\src\wpf\InsertingSeparators
xcopy /Y .\11-MasterDetailThreeLevels\src\wpf\MasterDetailThreeLevel\AssemblyInfo.cs .\21-CustomSorting\src\wpf\CustomSorting
xcopy /Y .\11-MasterDetailThreeLevels\src\wpf\MasterDetailThreeLevel\AssemblyInfo.cs .\24-AsynchronousBinding\src\wpf\AsynchronousBinding
xcopy /Y .\11-MasterDetailThreeLevels\src\wpf\MasterDetailThreeLevel\AssemblyInfo.cs .\25-BindToEnum\src\wpf\BindToEnum
xcopy /Y .\11-MasterDetailThreeLevels\src\wpf\MasterDetailThreeLevel\AssemblyInfo.cs .\26-DataTriggerSample\src\wpf\DataTriggerSample
xcopy /Y .\11-MasterDetailThreeLevels\src\wpf\MasterDetailThreeLevel\AssemblyInfo.cs .\27-ConvertXaml\src\wpf\ConvertXaml
xcopy /Y .\11-MasterDetailThreeLevels\src\wpf\MasterDetailThreeLevel\AssemblyInfo.cs .\28-FilterSample\src\wpf\FilterSample
xcopy /Y .\11-MasterDetailThreeLevels\src\wpf\MasterDetailThreeLevel\AssemblyInfo.cs .\29-MultipleFilters\src\wpf\MultipleFilters
xcopy /Y .\11-MasterDetailThreeLevels\src\wpf\MasterDetailThreeLevel\AssemblyInfo.cs .\30-MultiBindingConverter\src\wpf\MultiBindingConverter
xcopy /Y .\11-MasterDetailThreeLevels\src\wpf\MasterDetailThreeLevel\AssemblyInfo.cs .\31-ChangesMultithreading\src\wpf\ChangesMultithreading
xcopy /Y .\11-MasterDetailThreeLevels\src\wpf\MasterDetailThreeLevel\AssemblyInfo.cs .\32-PolygonBinding\src\wpf\PolygonBinding
xcopy /Y .\11-MasterDetailThreeLevels\src\wpf\MasterDetailThreeLevel\AssemblyInfo.cs .\33-PolygonBinding2\src\wpf\PolygonBinding2
xcopy /Y .\11-MasterDetailThreeLevels\src\wpf\MasterDetailThreeLevel\AssemblyInfo.cs .\34-PolygonBinding3\src\wpf\PolygonBinding3
xcopy /Y .\11-MasterDetailThreeLevels\src\wpf\MasterDetailThreeLevel\AssemblyInfo.cs .\35-CommonQuestions\src\wpf\CommonQuestions
xcopy /Y .\11-MasterDetailThreeLevels\src\wpf\MasterDetailThreeLevel\AssemblyInfo.cs .\36-ADOIndependentView\src\wpf\ADOIndependentView
xcopy /Y .\11-MasterDetailThreeLevels\src\wpf\MasterDetailThreeLevel\AssemblyInfo.cs .\37-PlanetsListBox\src\wpf\PlanetsListBox
xcopy /Y .\11-MasterDetailThreeLevels\src\wpf\MasterDetailThreeLevel\AssemblyInfo.cs .\38-UpdateExplicit\src\wpf\UpdateExplicit
xcopy /Y .\11-MasterDetailThreeLevels\src\wpf\MasterDetailThreeLevel\AssemblyInfo.cs .\39-TreeViewPerformancePart1\src\wpf\TreeViewPerformancePart1
xcopy /Y .\11-MasterDetailThreeLevels\src\wpf\MasterDetailThreeLevel\AssemblyInfo.cs .\40-TreeViewPerformancePart2\src\wpf\TreeViewPerformancePart2
xcopy /Y .\11-MasterDetailThreeLevels\src\wpf\MasterDetailThreeLevel\AssemblyInfo.cs .\41-TreeViewPerformancePart3\src\wpf\TreeViewPerformancePart3
xcopy /Y .\11-MasterDetailThreeLevels\src\wpf\MasterDetailThreeLevel\AssemblyInfo.cs .\42-WPFPresenter\src\wpf\WPFPresenter
xcopy /Y .\11-MasterDetailThreeLevels\src\wpf\MasterDetailThreeLevel\AssemblyInfo.cs .\43-BindToXLinq\src\wpf\BindToXLinq
xcopy /Y .\11-MasterDetailThreeLevels\src\wpf\MasterDetailThreeLevel\AssemblyInfo.cs .\44-XLinqXMLMasterDetail\src\wpf\XLinqXMLMasterDetail
xcopy /Y .\11-MasterDetailThreeLevels\src\wpf\MasterDetailThreeLevel\AssemblyInfo.cs .\45-DebuggingDataBinding\src\wpf\DebuggingDataBinding
xcopy /Y .\11-MasterDetailThreeLevels\src\wpf\MasterDetailThreeLevel\AssemblyInfo.cs .\46-DragDropListBox\src\wpf\DragDropListBox
xcopy /Y .\11-MasterDetailThreeLevels\src\wpf\MasterDetailThreeLevel\AssemblyInfo.cs .\47-ExpandTreeViewPart1\src\wpf\ExpandTreeViewPart1
xcopy /Y .\11-MasterDetailThreeLevels\src\wpf\MasterDetailThreeLevel\AssemblyInfo.cs .\48-ExpandTreeViewPart2\src\wpf\ExpandTreeViewPart2
xcopy /Y .\11-MasterDetailThreeLevels\src\wpf\MasterDetailThreeLevel\AssemblyInfo.cs .\49-ExpandTreeViewPart3\src\wpf\ExpandTreeViewPart3
xcopy /Y .\11-MasterDetailThreeLevels\src\wpf\MasterDetailThreeLevel\AssemblyInfo.cs .\51-UIVirtualization\src\wpf\UIVirtualization
xcopy /Y .\11-MasterDetailThreeLevels\src\wpf\MasterDetailThreeLevel\AssemblyInfo.cs .\52-DataVirtualization\src\wpf\DataVirtualization
xcopy /Y .\11-MasterDetailThreeLevels\src\wpf\MasterDetailThreeLevel\AssemblyInfo.cs .\54-PieChartWithLabels\src\wpf\PieChartWithLabels
xcopy /Y .\11-MasterDetailThreeLevels\src\wpf\MasterDetailThreeLevel\AssemblyInfo.cs .\55-PieChartWithLabelsSilverlight\src\wpf\PieChartWithLabelsSilverlight
xcopy /Y .\11-MasterDetailThreeLevels\src\wpf\MasterDetailThreeLevel\AssemblyInfo.cs .\56-PieChartWithLabelsSilverlight\src\wpf\PieChartWithLabelsSilverlight
xcopy /Y .\11-MasterDetailThreeLevels\src\wpf\MasterDetailThreeLevel\AssemblyInfo.cs .\57-DataVirtualization\src\wpf\DataVirtualization
xcopy /Y .\11-MasterDetailThreeLevels\src\wpf\MasterDetailThreeLevel\AssemblyInfo.cs .\58-MultipleStyles\src\wpf\MultipleStyles
xcopy /Y .\11-MasterDetailThreeLevels\src\wpf\MasterDetailThreeLevel\AssemblyInfo.cs .\59-WPFCollectionViewSource\src\wpf\WPFCollectionViewSource
xcopy /Y .\11-MasterDetailThreeLevels\src\wpf\MasterDetailThreeLevel\AssemblyInfo.cs .\60-SLCollectionViewSource\src\wpf\SLCollectionViewSource
xcopy /Y .\11-MasterDetailThreeLevels\src\wpf\MasterDetailThreeLevel\AssemblyInfo.cs .\61-OredevComputerWeekly\src\wpf\OredevComputerWeekly
xcopy /Y .\11-MasterDetailThreeLevels\src\wpf\MasterDetailThreeLevel\AssemblyInfo.cs .\62-DataVirtualizationFiltering\src\wpf\DataVirtualizationFiltering
xcopy /Y .\11-MasterDetailThreeLevels\src\wpf\MasterDetailThreeLevel\AssemblyInfo.cs .\64-DataVirtualizationFilteringSorting\src\wpf\DataVirtualizationFilteringSorting
xcopy /Y .\11-MasterDetailThreeLevels\src\wpf\MasterDetailThreeLevel\AssemblyInfo.cs .\66-SortingHierarchy\src\wpf\SortingHierarchy
xcopy /Y .\11-MasterDetailThreeLevels\src\wpf\MasterDetailThreeLevel\AssemblyInfo.cs .\67-PieChartWithLabelsUpdates\src\wpf\PieChartWithLabelsUpdates
xcopy /Y .\11-MasterDetailThreeLevels\src\wpf\MasterDetailThreeLevel\AssemblyInfo.cs .\69-BindRadioButtonsToEnumsPart1\src\wpf\BindRadioButtonsToEnumsPart1
xcopy /Y .\11-MasterDetailThreeLevels\src\wpf\MasterDetailThreeLevel\AssemblyInfo.cs .\70-BindRadioButtonsToEnumsPart2\src\wpf\BindRadioButtonsToEnumsPart2
xcopy /Y .\11-MasterDetailThreeLevels\src\wpf\MasterDetailThreeLevel\AssemblyInfo.cs .\71-BindRadioButtonsToEnumsPart3\src\wpf\BindRadioButtonsToEnumsPart3
xcopy /Y .\11-MasterDetailThreeLevels\src\wpf\MasterDetailThreeLevel\AssemblyInfo.cs .\72-BindRadioButtonsToEnumsPart4\src\wpf\BindRadioButtonsToEnumsPart4
xcopy /Y .\11-MasterDetailThreeLevels\src\wpf\MasterDetailThreeLevel\AssemblyInfo.cs .\73-BindRadioButtonsToEnumsPart5\src\wpf\BindRadioButtonsToEnumsPart5
xcopy /Y .\11-MasterDetailThreeLevels\src\wpf\MasterDetailThreeLevel\AssemblyInfo.cs .\74-PositioningDataBoundItems\src\wpf\PositioningDataBoundItems
xcopy /Y .\11-MasterDetailThreeLevels\src\wpf\MasterDetailThreeLevel\AssemblyInfo.cs .\75-SimultaneousEnableDisable\src\wpf\SimultaneousEnableDisable
xcopy /Y .\11-MasterDetailThreeLevels\src\wpf\MasterDetailThreeLevel\AssemblyInfo.cs .\76-FocusWatcher\src\wpf\FocusWatcher
xcopy /Y .\11-MasterDetailThreeLevels\src\wpf\MasterDetailThreeLevel\AssemblyInfo.cs .\77-CaptureWatcher\src\wpf\CaptureWatcher
xcopy /Y .\11-MasterDetailThreeLevels\src\wpf\MasterDetailThreeLevel\AssemblyInfo.cs .\78-BetterBindableBase\src\wpf\BetterBindableBase
xcopy /Y .\11-MasterDetailThreeLevels\src\wpf\MasterDetailThreeLevel\AssemblyInfo.cs .\79-BooleanConverters\src\wpf\BooleanConverters
